
[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#d2d4de"
yellow = "#e9b189"

[colors.cursor]
cursor = "0xc0ca8e"

[colors.normal]
black = "#161821"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#c6c8d1"
yellow = "#e2a478"

[colors.primary]
background = "#161821"
foreground = "#d2d4de"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
builtin_box_drawing = true
size = 16.0

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen Console NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "HackGen Console NF"
style = "Italic"

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Command"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
blur = true
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
working_directory = "None"
