[tools]
aws-vault = "latest"
awscli = "2.27.49"
gcloud = "latest"
gh = "latest"
go = "1.25.0"
nodejs = "23.7.0"
python = "3.12.0"
sops = "3.11.0"
terraform = "1.13.4"
terragrunt = "0.83.0"
usage = "latest"
